### ISSUE TITLE
Bitte um Info zu superuser-Review

### ISSUE THREAD

**Issue by 2xB** [2xB/talk#2]
Hallo @syslogic,

gestern haben Sie eine Änderung abgelehnt, die ich an einem superuser-Beitrag vorgeschlagen habe:
https://superuser.com/review/suggested-edits/1100357

Leider werde ich aus dem Review-Kommentar nicht wirklich schlau, warum meine Änderung für Sie problematisch war. Laut manpage von `sysctl` und eigenem Test lädt `sysctl -p` die in der vorherigen Zeile angelegte Datei nicht nach, `sysctl --system` allerdings schon.

Wäre es möglich, kurz das Problem darzustellen, damit ich in Zukunft darauf aufpassen kann?

Vielen Dank schonmal, viele Grüße und ein frohes neues Jahr!

**Comment by syslogic** [comment]
Vielleicht einfach mal `manpages sysctl` lesen?

**Comment by 2xB** [comment]
Vielen Dank für die schnelle Rückmeldung! Wenn mein Edit tatsächlich unsinnig ist, ist ablehnen definitiv richtig. Das entsprechende Meta nutzen ist ein guter Hinweis, mache ich in Zukunft gerne. Hier würde ich jetzt hinnehmen, dass wir die entsprechenden Abschnitte aus `man sysctl` einfach unterschiedlich lesen oder unterschiedliche Versionen haben und die Antwort so wie sie jetzt ist tatsächlich gewünscht ist.
